name: 'Admin Theme'
description: 'Setup the admin UI.'
type: 'Backend'
install:
  - thunder_branding
  - gin
  - gin_toolbar
  - help
  - navigation
config:
  import:
    gin: '*'
    navigation: '*'
  actions:
    system.theme:
      simpleConfigUpdate:
        admin: gin
    gin.settings:
      simpleConfigUpdate:
        preset_accent_color: custom

