name: 'Admin Theme'
description: 'Setup the admin UI.'
type: 'Backend'
install:
  - gin
  - gin_toolbar
  - help
  - navigation
config:
  import:
    gin: '*'
    navigation: '*'
  actions:
    system.theme:
      simple_config_update:
        admin: gin
