name: 'Thunder CNS'
description: 'Provides Thunder site with publishing features pre-configured.'
type: 'Site'
recipes:
  - core/recipes/standard
  - thunder_admin_theme
  - thunder_frontend_theme
  - thunder_sitemap
