name: thunder-cms-develop
type: drupal
docroot: docroot
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
hooks:
  post-start:
    # Add the components as path repositories.
    - exec-host: "ddev setup-repositories"
web_environment:
  # For faster performance, don't audit dependencies automatically.
  - COMPOSER_NO_AUDIT=1
